In [1]:
import pandas as pd
from pathlib import Path
import json
import ast

In [10]:
path = Path(r"../important_results/sample_500_meta_gpt_direct_results.csv")
df = pd.read_csv(path)

In [11]:
len(df)

500

In [13]:
n = 10

ad_texts = df['ad_text'][:n]
gpt_results = df['gpt_toulmin_json'][:n]
for ad_text, result in zip(ad_texts, gpt_results):
    print(f"ad_text: \n {ad_text}")
    print(f"gpt_result: \n {result}")

ad_text:
 🛑🚨🛑🚨Protecting the Endangerment Finding = Protecting Children's Health! Moms across the country share what rolling back this foundational protection for regulating climate emissions means to them. Listen in and then tell EPA to do its job and keep cutting climate pollution!
gpt_result:
 {"claim": "Protecting the Endangerment Finding protects children's health.", "ground": "Not present", "warrant": "Not present"}
ad_text:
 Stop Kamala's Radical Plan for America Before It's Too Late

Kamala Harris is dangerously liberal, and her extreme policies threaten to fundamentally weaken our nation. Under her leadership, America could face devastating consequences: higher taxes, lenient crime policies, and an alarming erosion of our freedoms. Harris's radical agenda includes fighting to set murderers free, embracing the disastrous "Bidenomics" that dismisses rising costs, and imposing more taxes on the middle class under the guise of "fair share." She advocates for abolishing borders, reviving the Green New Deal, and granting freedom to individuals involved in violent behavior—what she calls "ending wrongheaded thinking" that more police means safer communities. Harris also seeks to eliminate private health insurance and extend Social Security and Medicare benefits to illegal aliens. The future of our country is at stake—don’t let Kamala Harris lead America down this dangerous path.  https://kamala2024policies.com/
gpt_result:
 {"claim": "Kamala Harris's radical policies threaten to fundamentally weaken the nation and lead America down a dangerous path.", "ground": "Her agenda includes fighting to set murderers free, embracing 'Bidenomics,' imposing more taxes on the middle class, abolishing borders, reviving the Green New Deal, granting freedom to individuals involved in violent behavior, seeking to eliminate private health insurance, and extending Social Security and Medicare benefits to illegal aliens.", "warrant": "Not present"}
ad_text:
 Conduct undergraduate research using next-gen DNA sequencing—aboard a sailing research vessel in the Sargasso Sea. Present your work to scientists and policymakers during an end of semester symposium in Woods Hole, MA.
gpt_result:
 {"claim": "Not present", "ground": "Not present", "warrant": "Not present"}
ad_text:
 Governor Whitmer: The people working in the Michigan Department of Corrections facilities are demanding your attention.
—————————————-
The statics being reported about the Michigan Department of Corrections are misleading at best. It’s time to show the REAL numbers and hear the REAL voices that have to endure this dangerous job which is at a critical point.
As your State Representative in Northern Michigan, I’m going to bring your voice to Lansing in a whole new way.
👉I ask you to please get out and VOTE THIS TUESDAY to keep me in this fight!
gpt_result:
 {"claim": "You should vote this Tuesday to keep the speaker in the fight for the people working in the Michigan Department of Corrections facilities.", "ground": "The statistics being reported about the Michigan Department of Corrections are misleading at best. It’s time to show the real numbers and hear the real voices that have to endure this dangerous job which is at a critical point.", "warrant": "Not present"}
ad_text:
 One of the things I love about singing this song by Rabbi David Zeller is that as we sing the words “I am alive,” the tune can feel mournful and aching in its celebration of aliveness.

So I have to wonder, what is aliveness if not to include the great sorrows and aches of the heart and body? What is aliveness if not to include the pain of the world around us? What is aliveness if not to include death and destruction?

As the song asks “And who is this aliveness that I am?” - I have to ask, aren’t we, too, blessed and holy by the painful magnitude of it all? “Is it not the blessed holy one?” Aren’t we created in the image of the whole? Do we trust ourselves to hold the whole, to be the whole, to accept this greatness?

My heart goes out to all of you hurting now - whether in grief for the fires, the wars, the hostages, the ceasefire, the impending leadership of America, every country and its craziness, climate change, the future, your children, our children- and all the other reasons you want to delete this instagram app asap. All of this aliveness that feels like too much.

My heart goes out to you. I pray we can always find a way to sing through this grief, to sing a pathway through the dark.

From my aching heart, to yours. ❤️‍🩹
gpt_result:
 {"claim": "Aliveness includes great sorrows, aches, pain, death, and destruction.", "ground": "The mournful and aching tune of the song in celebration of aliveness; questioning what aliveness is if not to include pain and sorrow.", "warrant": "Not present"}
ad_text:
 Grateful for federal support in North Carolina! Thanks to bipartisan efforts, our housing and commercial sectors are thriving. Here's to continued growth and community building! 🏡🌆 #NorthCarolina #BipartisanSupport
gpt_result:
 {"claim": "Thanks to bipartisan federal support, North Carolina's housing and commercial sectors are thriving.", "ground": "Grateful for federal support in North Carolina; our housing and commercial sectors are thriving.", "warrant": "Not present"}
ad_text:
 Support Sonola Segun’s Recycling Initiative for a Sustainable Future
https://gofund.me/8bd729e2

Hello, my name is Sonola Segun, a passionate public health graduate living with sickle cell disease. Despite facing numerous health challenges, financial struggles, and personal losses, I remain committed to making a positive impact on public health and environmental sustainability.

Why This Recycling Business Matters

Living with sickle cell disease has shown me how environmental factors—like pollution and poor waste management—can worsen chronic health conditions. A cleaner, healthier environment isn’t just a luxury; it’s essential. That’s why I’m launching a recycling business focused on:

Reducing waste

Educating communities about recycling and sustainability

Promoting better waste management practices

What I’ve Achieved So Far

I’ve already secured:

Permits & Licenses

Business Registration

Collection Containers

Sorting Equipment

Educational Flyers & Training Materials

However, I need your support to take the final steps and make this vision a reality.

What Your Support Will Fund

To launch effectively, I need help with:

1. Manual Sorting Costs: $390

2. Shredders: $3,000

3. Truck/Van for Transportation: $2,000

Total Goal: $5,390

The Impact of Your Contribution

Your donation will:

Create local jobs and boost the economy

Raise awareness about recycling and public health

Improve waste management practices

Reduce environmental damage caused by poor waste disposal

Join Me in Building a Greener Future

Every contribution, no matter how small, brings us closer to a cleaner, healthier world. Together, we can create an initiative that benefits public health, the environment, and future generations.

Thank you for your support and belief in this mission.

Sincerely,
Sonola Segun
Public Health Advocate & Sustainability Entrepreneur

@[409775382063100:69:GofundMe and Fundraising campaigns/Sharing and Receiving Donation] @[100076010047236:2048:CFI Group Arabic] @[1325131591574313:69:GoFundMe Share And Support] @[1500204146692093:69:GoFundMe Money Donations] #indiegogo #gofundme #spotfund #FreePalestine #usa #kickstarter #GazaGenocide #chuffed #Rusia #australia #mexico @[100026251867352:2048:Tae White] #allnations
gpt_result:
 {"claim": "Supporting Sonola Segun’s recycling initiative will help create local jobs, raise awareness about recycling and public health, improve waste management practices, and reduce environmental damage.", "ground": "Sonola Segun has secured permits, licenses, business registration, collection containers, sorting equipment, educational flyers, and training materials, but needs additional funds for manual sorting costs, shredders, and transportation to launch the recycling business. Living with sickle cell disease has shown her how environmental factors can worsen health conditions.", "warrant": "A recycling business that improves waste management and educates communities will create local jobs, benefit public health and the environment, and reduce environmental damage."}
ad_text:
 Hoosier communities are benefiting from unleashing America’s energy dominance:

“So that tax revenue’s coming in, and it’s helping everyone in the community: the local townships, the fire and safety, the libraries, the schools, and the local units.” - Steve B., White County, IN Commissioner
gpt_result:
 {"claim": "Hoosier communities are benefiting from unleashing America’s energy dominance.", "ground": "Tax revenue is coming in and helping everyone in the community: the local townships, the fire and safety, the libraries, the schools, and the local units.", "warrant": "Not present"}
ad_text:
 Time & time again we see how most of our elected officials continue to fail at protecting our health & safety, which is why we need YOUR help to create the world that we want to live in. For more information on how to get involved, click the link in our bio to our landing page to sign up to be involved in upcoming rulemakings and engagement opportunities 🪴✨

#environment #climate #legislation #policy #environment #climatecrisis #community #love #joy #resilence #pollution #solutions #action #hope #climatecrisis #denver #denvercolorado
gpt_result:
 {"claim": "We need your help to create the world that we want to live in.", "ground": "Most of our elected officials continue to fail at protecting our health and safety.", "warrant": "Not present"}
ad_text:
 “We’re the third fastest warming city in the nation here in Tucson, and Phoenix is fourth”
gpt_result:
 {"claim": "Tucson is the third fastest warming city in the nation and Phoenix is fourth.", "ground": "Not present", "warrant": "Not present"}

In [14]:
print(df['gpt_toulmin_json'][0])

{"claim": "Protecting the Endangerment Finding protects children's health.", "ground": "Not present", "warrant": "Not present"}

In [15]:
path = Path(r"../important_results/sample_500_meta_gpt_results.csv")
df2 = pd.read_csv(path)

In [9]:
print(df2['gpt_toulmin_json'][0])

{"claim": "Protecting the Endangerment Finding protects children's health.", "ground": "Moms across the country share what rolling back this foundational protection for regulating climate emissions means to them.", "warrant": "Not present"}

In [16]:
ad_texts = df2['ad_text'][:n]
gpt_results = df2['gpt_toulmin_json'][:n]
for ad_text, result in zip(ad_texts, gpt_results):
    print(f"ad_text: \n {ad_text}")
    print(f"gpt_result: \n {result}")

ad_text:
 🛑🚨🛑🚨Protecting the Endangerment Finding = Protecting Children's Health! Moms across the country share what rolling back this foundational protection for regulating climate emissions means to them. Listen in and then tell EPA to do its job and keep cutting climate pollution!
gpt_result:
 {"claim": "Protecting the Endangerment Finding protects children's health.", "ground": "Moms across the country share what rolling back this foundational protection for regulating climate emissions means to them.", "warrant": "Not present"}
ad_text:
 Stop Kamala's Radical Plan for America Before It's Too Late

Kamala Harris is dangerously liberal, and her extreme policies threaten to fundamentally weaken our nation. Under her leadership, America could face devastating consequences: higher taxes, lenient crime policies, and an alarming erosion of our freedoms. Harris's radical agenda includes fighting to set murderers free, embracing the disastrous "Bidenomics" that dismisses rising costs, and imposing more taxes on the middle class under the guise of "fair share." She advocates for abolishing borders, reviving the Green New Deal, and granting freedom to individuals involved in violent behavior—what she calls "ending wrongheaded thinking" that more police means safer communities. Harris also seeks to eliminate private health insurance and extend Social Security and Medicare benefits to illegal aliens. The future of our country is at stake—don’t let Kamala Harris lead America down this dangerous path.  https://kamala2024policies.com/
gpt_result:
 {"claim": "Kamala Harris's policies are dangerous and would fundamentally weaken America, so her plan for America must be stopped.", "ground": "Her policies include higher taxes, lenient crime policies, erosion of freedoms, fighting to set murderers free, implementing Bidenomics that dismisses rising costs, imposing more taxes on the middle class, advocating for abolishing borders, reviving the Green New Deal, granting freedom to violent individuals, seeking to eliminate private health insurance, and extending Social Security and Medicare benefits to illegal aliens.", "warrant": "Not present"}
ad_text:
 Conduct undergraduate research using next-gen DNA sequencing—aboard a sailing research vessel in the Sargasso Sea. Present your work to scientists and policymakers during an end of semester symposium in Woods Hole, MA.
gpt_result:
 {"claim": "Not present", "ground": "Not present", "warrant": "Not present"}
ad_text:
 Governor Whitmer: The people working in the Michigan Department of Corrections facilities are demanding your attention.
—————————————-
The statics being reported about the Michigan Department of Corrections are misleading at best. It’s time to show the REAL numbers and hear the REAL voices that have to endure this dangerous job which is at a critical point.
As your State Representative in Northern Michigan, I’m going to bring your voice to Lansing in a whole new way.
👉I ask you to please get out and VOTE THIS TUESDAY to keep me in this fight!
gpt_result:
 {"claim": "You should vote this Tuesday to keep me in this fight as your State Representative.", "ground": "The statistics being reported about the Michigan Department of Corrections are misleading and the job is dangerous and at a critical point.", "warrant": "Not present"}
ad_text:
 One of the things I love about singing this song by Rabbi David Zeller is that as we sing the words “I am alive,” the tune can feel mournful and aching in its celebration of aliveness.

So I have to wonder, what is aliveness if not to include the great sorrows and aches of the heart and body? What is aliveness if not to include the pain of the world around us? What is aliveness if not to include death and destruction?

As the song asks “And who is this aliveness that I am?” - I have to ask, aren’t we, too, blessed and holy by the painful magnitude of it all? “Is it not the blessed holy one?” Aren’t we created in the image of the whole? Do we trust ourselves to hold the whole, to be the whole, to accept this greatness?

My heart goes out to all of you hurting now - whether in grief for the fires, the wars, the hostages, the ceasefire, the impending leadership of America, every country and its craziness, climate change, the future, your children, our children- and all the other reasons you want to delete this instagram app asap. All of this aliveness that feels like too much.

My heart goes out to you. I pray we can always find a way to sing through this grief, to sing a pathway through the dark.

From my aching heart, to yours. ❤️‍🩹
gpt_result:
 {"claim": "We should find ways to sing through grief and hardship, embracing all aspects of aliveness, including sorrow and pain.", "ground": "My heart goes out to all of you hurting now - whether in grief for the fires, the wars, the hostages, the ceasefire, the impending leadership of America, every country and its craziness, climate change, the future, your children, our children- and all the other reasons you want to delete this instagram app asap. All of this aliveness that feels like too much. My heart goes out to you. I pray we can always find a way to sing through this grief, to sing a pathway through the dark.", "warrant": "Not present"}
ad_text:
 Grateful for federal support in North Carolina! Thanks to bipartisan efforts, our housing and commercial sectors are thriving. Here's to continued growth and community building! 🏡🌆 #NorthCarolina #BipartisanSupport
gpt_result:
 {"claim": "Federal support and bipartisan efforts contribute to the thriving of housing and commercial sectors in North Carolina.", "ground": "Thanks to bipartisan efforts, our housing and commercial sectors are thriving.", "warrant": "Not present"}
ad_text:
 Support Sonola Segun’s Recycling Initiative for a Sustainable Future
https://gofund.me/8bd729e2

Hello, my name is Sonola Segun, a passionate public health graduate living with sickle cell disease. Despite facing numerous health challenges, financial struggles, and personal losses, I remain committed to making a positive impact on public health and environmental sustainability.

Why This Recycling Business Matters

Living with sickle cell disease has shown me how environmental factors—like pollution and poor waste management—can worsen chronic health conditions. A cleaner, healthier environment isn’t just a luxury; it’s essential. That’s why I’m launching a recycling business focused on:

Reducing waste

Educating communities about recycling and sustainability

Promoting better waste management practices

What I’ve Achieved So Far

I’ve already secured:

Permits & Licenses

Business Registration

Collection Containers

Sorting Equipment

Educational Flyers & Training Materials

However, I need your support to take the final steps and make this vision a reality.

What Your Support Will Fund

To launch effectively, I need help with:

1. Manual Sorting Costs: $390

2. Shredders: $3,000

3. Truck/Van for Transportation: $2,000

Total Goal: $5,390

The Impact of Your Contribution

Your donation will:

Create local jobs and boost the economy

Raise awareness about recycling and public health

Improve waste management practices

Reduce environmental damage caused by poor waste disposal

Join Me in Building a Greener Future

Every contribution, no matter how small, brings us closer to a cleaner, healthier world. Together, we can create an initiative that benefits public health, the environment, and future generations.

Thank you for your support and belief in this mission.

Sincerely,
Sonola Segun
Public Health Advocate & Sustainability Entrepreneur

@[409775382063100:69:GofundMe and Fundraising campaigns/Sharing and Receiving Donation] @[100076010047236:2048:CFI Group Arabic] @[1325131591574313:69:GoFundMe Share And Support] @[1500204146692093:69:GoFundMe Money Donations] #indiegogo #gofundme #spotfund #FreePalestine #usa #kickstarter #GazaGenocide #chuffed #Rusia #australia #mexico @[100026251867352:2048:Tae White] #allnations
gpt_result:
 {"claim": "You should support Sonola Segun’s Recycling Initiative for a sustainable future.", "ground": "Your donation will create local jobs and boost the economy, raise awareness about recycling and public health, improve waste management practices, and reduce environmental damage caused by poor waste disposal.", "warrant": "Not present"}
ad_text:
 Hoosier communities are benefiting from unleashing America’s energy dominance:

“So that tax revenue’s coming in, and it’s helping everyone in the community: the local townships, the fire and safety, the libraries, the schools, and the local units.” - Steve B., White County, IN Commissioner
gpt_result:
 {"claim": "Hoosier communities are benefiting from unleashing America’s energy dominance.", "ground": "Tax revenue is coming in and helping everyone in the community: the local townships, the fire and safety, the libraries, the schools, and the local units.", "warrant": "Not present"}
ad_text:
 Time & time again we see how most of our elected officials continue to fail at protecting our health & safety, which is why we need YOUR help to create the world that we want to live in. For more information on how to get involved, click the link in our bio to our landing page to sign up to be involved in upcoming rulemakings and engagement opportunities 🪴✨

#environment #climate #legislation #policy #environment #climatecrisis #community #love #joy #resilence #pollution #solutions #action #hope #climatecrisis #denver #denvercolorado
gpt_result:
 {"claim": "We need your help to create the world that we want to live in.", "ground": "Most of our elected officials continue to fail at protecting our health and safety.", "warrant": "Not present"}
ad_text:
 “We’re the third fastest warming city in the nation here in Tucson, and Phoenix is fourth”
gpt_result:
 {"claim": "Not present", "ground": "“We’re the third fastest warming city in the nation here in Tucson, and Phoenix is fourth”", "warrant": "Not present"}

In [17]:
inputs = df['input']
input_prompts = df['input_prompt']
responses = df['response']

In [18]:
n = 10
for i in range(n):
    input = inputs[i]
    input_prompt = input_prompts[i]
    response = responses[i]
    print(f"Input: {input}")
    print(f"Input prompt: {input_prompt}\n\n")
    print(f"Output: {response}\n\n")

Input: Be bold! Be a peacemaker and talk climate!

Sign up today to receive tips and resources on how to have these conversations. There will also be a virtual workshop on practicing these skills that you will not want to miss!,Be bold! Be a peacemaker and talk climate!

Sign up today to receive tips and resources on how to have these conversations. There will also be a virtual workshop on practicing these skills that you will not want to miss!
Input prompt: "Be bold! Be a peacemaker and talk climate!

Sign up today to receive tips and resources on how to have these conversations. There will also be a virtual workshop on practicing these skills that you will not want to miss!,Be bold! Be a peacemaker and talk climate!

Sign up today to receive tips and resources on how to have these conversations. There will also be a virtual workshop on practicing these skills that you will not want to miss!"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: Ex-Wall Street Insider: "Make this one move to profit from the presidential election."
Input prompt: "Ex-Wall Street Insider: "Make this one move to profit from the presidential election.""

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: Are you in?
Input prompt: "Are you in?"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: Lead the climate-resilient economy of tomorrow with GARP’s Sustainability and Climate Risk (SCR®) Certificate. 🏆🌳,Lead the climate-resilient economy of tomorrow with GARP’s Sustainability and Climate Risk (SCR®) Certificate. 🏆🌳
Input prompt: "Lead the climate-resilient economy of tomorrow with GARP’s Sustainability and Climate Risk (SCR®) Certificate. 🏆🌳,Lead the climate-resilient economy of tomorrow with GARP’s Sustainability and Climate Risk (SCR®) Certificate. 🏆🌳"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: Behind the scenes recording:
"What Does Justice Look Like?"
by Waziyatawin, Ph.D.

Support your local bookstores by signing up and listening at:
https://libro.fm/audiobooks/9781937141387-what-does-justice-look-like?fbclid=IwY2xjawEzFn1leHRuA2FlbQIxMAABHSr_zh4AxjdVhFX03frnufeSAOljjZ500mKA_ZJDZOwl_QHYlWdLJvw1rQ_aem_1KDa4XbJiKBxgZOlpk_o1Q

 #LandBack  #colonialism  #audiobook #justice  #dakota  #truthtelling #Climateaction #coexist #hope #decolonize
Input prompt: "Behind the scenes recording:
"What Does Justice Look Like?"
by Waziyatawin, Ph.D.

Support your local bookstores by signing up and listening at:
https://libro.fm/audiobooks/9781937141387-what-does-justice-look-like?fbclid=IwY2xjawEzFn1leHRuA2FlbQIxMAABHSr_zh4AxjdVhFX03frnufeSAOljjZ500mKA_ZJDZOwl_QHYlWdLJvw1rQ_aem_1KDa4XbJiKBxgZOlpk_o1Q

 #LandBack  #colonialism  #audiobook #justice  #dakota  #truthtelling #Climateaction #coexist #hope #decolonize"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: Are big corporations owning up to the pollution they create? 🤔
Input prompt: "Are big corporations owning up to the pollution they create? 🤔"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Big corporations are owning up to the pollution they create.
Ground: Not present
Warrant: Not present


Input: Will Virginia have more say over solar laws in 2025?
Input prompt: "Will Virginia have more say over solar laws in 2025?"

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Not present
Warrant: Not present


Input: A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy.
Input prompt: "A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy."

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy.

Ground: Not present.

Warrant: Not present.


Input: Dan Wolgamott has worked to protect the air we breathe, the water we drink, and the health of our communities.,Dan Wolgamott has worked to protect the air we breathe, the water we drink, and the health of our communities.
Input prompt: "Dan Wolgamott has worked to protect the air we breathe, the water we drink, and the health of our communities.,Dan Wolgamott has worked to protect the air we breathe, the water we drink, and the health of our communities."

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Dan Wolgamott has worked to protect the air we breathe, the water we drink, and the health of our communities.
Warrant: Not present


Input: Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.
Input prompt: "Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages.,Clean Power Alliance offers a $750 rebate toward eligible solar battery systems that lower your bill and sustainably power your home, even during outages."

 Please define above Toulmin components explicitly:
Claim: disputable position or judgment.
Ground: evidence or reasons explicitly stated.
Warrant: assumption linking ground to
claim.
Instructions:
- Components may be absent.
- Output “Not present” if missing.
- Do not infer or add unstated informa-
tion.
- If text is purely factual or descriptive,
indicate that no claim is present.


Output: Claim: Not present
Ground: Clean Power Alliance offers a $750 rebate toward eligible solar battery systems.
Warrant: Not present

In [3]:
path = Path(r"../results/sample_500_meta_result_format_result_support_result.csv")
df = pd.read_csv(path)
inputs = df['input']
input_prompts = df['input_prompt']
responses = df['response']
metadata = df['metadata']

In [4]:
keys = df['llm_theme'].unique()

In [12]:
print(keys)

['**"Pro-solar advocacy"**' '**"Solar energy advocacy"**'
 '**"Ocean conservation call"**' '**"Local civic engagement"**'
 '**"Solar emergency power"**' '**"Public climate input"**'
 '**"Climate crisis advocacy"**' '**"Anti-Harris energy attack"**'
 '**"Big Oil accountability"**' '**"Clean energy advocacy"**'
 '**"Pro-climate candidate"**' '**"Pro-infrastructure investment"**'
 '**"Pro-clean energy jobs"**' '**"Pro-recycling advocacy"**'
 '**"Pro-nuclear advocacy"**' '**"Climate education advocacy"**'
 '**"Methane regulation push"**' '**"Local food advocacy"**'
 '**"Pro-BESS advocacy"**' '**"Ethical fashion advocacy"**'
 '**"Clean water advocacy"**' '**"Oil industry promotion"**'
 '**"SAF advocacy push"**' nan '**"Energy cost alarm"**'
 '**"Green building advocacy"**' '**"Pro-wind energy"**'
 '**"Sustainable farming progress"**' '**"Pro-forest climate action"**'
 '**"Climate voter mobilization"**' '**"Clean energy boom"**'
 '**"Anti-coal advocacy"**' '**"Clean air advocacy"**'
 '**"Agriculture policy updates"**' '**"Farmland renewables boost"**'
 '**"Pro-clean energy"**' '**"Ethanol advocacy"**']

In [19]:
key = keys[1]
print(key)
data = df[(df['llm_theme'] == key) & (df['response'] == 'Yes')]
claims = data['claim']
print(claims)
print(claims.iloc[1])

**"Solar energy advocacy"**
35     ['Solar energy is a viable option for farmers'...
46     ['Solar projects support local schools, commun...
79     ['The City of Lebanon, Ohio is partnering with...
151    ['One of the most significant benefits of comm...
Name: claim, dtype: object
['Solar projects support local schools, communities, and more', 'Solar energy helps communities invest in a healthy and sustainable future']

In [10]:
data = df[(df['llm_theme'] == key) & (df['response'] == 'Not related')]
claims = data['claim']
print(claims)

42                                                    []
106    ['Bruce, a Georgia resident, continues to work...
Name: claim, dtype: object

In [22]:
path = Path(r"../results/sample_500_bluesky_result_format_result_support_result.csv")
df = pd.read_csv(path)
df.head(5)

,id,input,input_prompt,response,claim,llm_theme,metadata
0,13,"...yes, maybe AI hallucinations, welcomed by (...",Task: Determine whether the claim supports the...,Yes,"[""AI hallucinations are being welcomed by auth...",Science under attack,"{'Unnamed: 0': 13, 'input': ""...yes, maybe AI ..."
1,35,That's the point! You've handed anyone who wa...,Task: Determine whether the claim supports the...,Yes,['Scientists are willing to lie and obfuscate ...,Science under attack,"{'Unnamed: 0': 35, 'input': ""That's the point!..."
2,27,This was the plan all along. Remember the atte...,Task: Determine whether the claim supports the...,Not related,['This was the plan all along.'],Climate rollbacks,"{'Unnamed: 0': 27, 'input': 'This was the plan..."
3,17,End an 80% done project that will provide jobs...,Task: Determine whether the claim supports the...,Not related,"[""This Administration doesn't care about the e...",Climate rollbacks,"{'Unnamed: 0': 17, 'input': ""End an 80% done p..."
4,22,Great to bring MPs from across parties togethe...,Task: Determine whether the claim supports the...,Yes,['The future of large-scale solar and renewabl...,Climate action collaboration,"{'Unnamed: 0': 22, 'input': 'Great to bring MP..."

In [23]:
keys = df['llm_theme'].unique()

In [24]:
print(keys)

['Science under attack' 'Climate rollbacks' 'Climate action collaboration'
 'End fossil fuels' "Oil's Deceptive Greed" 'Renewable Energy Momentum'
 'Responsible tourism future' 'Renewable energy surge'
 'MAGA Climate Deception' 'Deadly Heat Crisis' 'EV transition barriers'
 'Cleaning fatigue' 'Climate unease' 'Resource expansion drilling'
 'Fossil fuel deception' 'Greenwashing deception'
 'Starry night preservation' 'Green Energy Sovereignty'
 'Insurance Climate Urgency' 'Climate migration crisis'
 'Water pollution crisis' 'Deforestation & Wildlife Crisis'
 'Climate justice action' 'Corporate Climate Accountability'
 "Capitalism's climate doom" 'Climate-fueled wildfires'
 'Wildlife climate crisis' 'Fossil fuel corruption'
 'Fascism’s fatal flaws' 'Water resilience' 'Clean Energy Push'
 'Wealth vs. Welfare' 'Climate Denial Backlash'
 'Climate injustice exposed' 'Anti-renewable hypocrisy'
 'Coffee climate crisis' "China's green leap"
 'Climate legal accountability']

In [25]:
key = keys[1]
print(key)
data = df[(df['llm_theme'] == key) & (df['response'] == 'Yes')]
claims = data['claim']
print(claims)
print(claims.iloc[1])

Climate rollbacks
25     ['The U.S. is abandoning important sectors suc...
35     ['Emissions from burning fossil fuels do not c...
42     ['Doug Ford government spent $231M to scrap gr...
45     ['Congress is about to kill a federal methane ...
82     ['Rolling back these protections means more ca...
96     ['His platform mirrors the Canadian Associatio...
103    ['Any Trump EPA Attempt to Stop Regulating Cli...
127    ['The government is blaming farmers for their ...
173    ['Trump is eliminating renewable and alternati...
182    ['Manufacturing will only come back to this co...
214    ['The rollback of environmental protections wi...
Name: claim, dtype: object
['Emissions from burning fossil fuels do not contribute significantly to dangerous pollution, climate change or public health.']

In [25]:
n = 10
for i in range(n):
    input = inputs[i]
    input_prompt = input_prompts[i]
    response = responses[i]
    print(f"Input: {input}")
    print(f"Input prompt: {input_prompt}\n\n")
    print(f"Output: {response}\n\n")

Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: Not present
Ground: Clean Power Alliance offers a $750 rebate toward eligible solar battery systems.
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Clean Power Alliance offers a $750 rebate toward eligible solar battery systems.
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": ["Not present"],
    "Ground": ["Clean Power Alliance offers a $750 rebate toward eligible solar battery systems."],
    "Warrant": ["Not present"]
}


Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: Not present
Ground: Not present
Warrant: Not present
Input prompt: """Claim: Not present
Ground: Not present
Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [],
    "Ground": [],
    "Warrant": []
}


Input: Claim: You can play a part in the next generation of clean energy and explore a career in nuclear energy.

Ground: Not present

Warrant: Not present
Input prompt: """Claim: You can play a part in the next generation of clean energy and explore a career in nuclear energy.

Ground: Not present

Warrant: Not present"""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [
        "You can play a part in the next generation of clean energy",
        "Explore a career in nuclear energy"
    ],
    "Ground": [
        "Not present"
    ],
    "Warrant": [
        "Not present"
    ]
}


Input: Claim: A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy.

Ground: Not present.

Warrant: Not present.
Input prompt: """Claim: A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy.

Ground: Not present.

Warrant: Not present."""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [
        "A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy."
    ],
    "Ground": [
        "Not present."
    ],
    "Warrant": [
        "Not present."
    ]
}


Input: Claim: As your representative, I will fight to defend our spectacular landscapes and work with you to protect the beauty in our valley and state.

Ground: We deliberately chose to raise our family in this area because of all of the ways we can connect with nature.

Warrant: Not present.
Input prompt: """Claim: As your representative, I will fight to defend our spectacular landscapes and work with you to protect the beauty in our valley and state.

Ground: We deliberately chose to raise our family in this area because of all of the ways we can connect with nature.

Warrant: Not present."""

 Format the above text in a Python dictionary with values as a list of bullet points.



Output: {
    "Claim": [
        "As your representative, I will fight to defend our spectacular landscapes and work with you to protect the beauty in our valley and state."
    ],
    "Ground": [
        "We deliberately chose to raise our family in this area because of all of the ways we can connect with nature."
    ],
    "Warrant": [
        "Not present."
    ]
}

In [16]:
OUTPUT_FILE = Path(f"../results/sample_500_bluesky_result.jsonl")
path = Path(OUTPUT_FILE)
records = []
with open(path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            print(line)

df = pd.DataFrame(records)

responses = df[1]
metadata = df[2]

In [ ]:
print(metadata[0])

{'cid': 'bafyreid2womneoiv463vkgng3kubgrafnm3szatdpih3ojvzklqcnr65yi',
 'text': "As if all of his servers don't create enough pollution?",
 'llm_theme_summ': 'Science under attack',
 'llm_theme_theme': 'Greenwashing deception',
 'lda_topic_id': 81,
 'lda_topic_keywords': 'pollution, air, city, show, focus',
 'bert_topic_keywords': 'air pollution, air, pollution, exposure, air quality, quality, pm2, airpollution, asthma, mask',
 'bert_topic_name': '1_air pollution_air_pollution_exposure',
 'lda_keywords_llm_truth': False,
 'bert_keywords__llm_truth': False,
 'llm_theme_llm_truth': False,
 'llm_summ_llm_truth': False,
 'lda_keywords_human_truth': 'No',
 'bert_keywords_human_truth': 'No',
 'llm_theme_human_truth': 'No',
 'llm_summ_human_truth': 'No',
 'Unnamed: 16': None,
 'Unnamed: 17': None,
 'Unnamed: 18': None,
 'Unnamed: 19': None,
 'row': 2,
 'input_prompt': '"As if all of his servers don\'t create enough pollution?"\n\n Please define above Toulmin components explicitly:\nClaim: disputable position or judgment.\nGround: evidence explicitly stated.\nWarrant: assumption linking ground to\nclaim.\nInstructions:\n- Components may be absent.\n- Output “Not present” if missing.\n- Do not infer or add unstated informa-\ntion.\n- If text is purely factual or descriptive,\nindicate that no claim is present.'}

In [ ]:
OUTPUT_FILE = Path(f"../results/sample_500_bluesky_result_format_result.csv")
df = pd.read_csv(OUTPUT_FILE)
df.head(5)

,Unnamed: 0,input,input_prompt,response,claim,ground,warrant,llm_theme_human_truth,llm_theme_llm_truth,llm_theme,metadata
0,0,Can somebody find a way of doing this for him ...,"""""""Claim: Not present\nGround: Not present\nWa...","{\n ""Claim"": [],\n ""Ground"": [],\n ""W...",[],[],[],Yes,False,Climate action collaboration,"{'id': 44, 'input': 'Can somebody find a way o..."
1,1,My bears coming over and I'm struggling to fin...,"""""""Claim: Not present\nGround: ""My bears comin...","{\n ""Claim"": [""Not present""],\n ""Ground""...",['Not present'],"[""My bears coming over and I'm struggling to f...",['Not present'],Yes,True,Cleaning fatigue,"{'id': 10, 'input': ""My bears coming over and ..."
2,2,"Some Memes, most real guesses. \n\nMy 2025 bin...","""""""Claim: Not present\nGround: Not present\nWa...","{\n ""Claim"": [],\n ""Ground"": [],\n ""W...",[],[],[],No,False,Climate unease,"{'id': 38, 'input': 'Some Memes, most real gue..."
3,3,"And, further, the least sustainable EV on the ...","""""""Claim: The least sustainable EV (Electric V...","{\n ""Claim"": [\n ""The least sustaina...",['The least sustainable EV (Electric Vehicle) ...,['Not present.'],['Not present.'],Yes,True,EV transition barriers,"{'id': 36, 'input': 'And, further, the least s..."
4,4,German-Canadian Raw Materials Alliance Strengt...,"""""""Claim: Not present\nGround: German-Canadian...","{\n ""Claim"": [""Not present""],\n ""Ground""...",['Not present'],['German-Canadian Raw Materials Alliance stren...,['Not present'],Yes,True,Renewable Energy Momentum,"{'id': 47, 'input': 'German-Canadian Raw Mater..."

In [8]:
OUTPUT_FILE = r'../results/sample_500_meta_result_format_result.jsonl'
path = Path(OUTPUT_FILE)
records = []
with open(path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            print(line)

df = pd.DataFrame(records)

responses = df[1]
metadata = df[2]

records = []
for i in range(len(df)):
    content = responses[i]['choices'][0]['message']['content']
    
    try:
        dct = json.loads(content)
    except:
        continue
    claim = dct.get("Claim", '')
    if claim is None:
        claim = dct.get('claim', '')
    ground = dct.get('Ground', '')
    warrant = dct.get('Warrant', '')

    md = metadata[i]
    input = md['input']
    input_prompt = md['input_prompt']

    mdmd = md.get('metadata', '')
    mdmd = ast.literal_eval(mdmd)
    llm_theme_human_truth = mdmd.get('llm_theme_human_truth', '')
    llm_theme_llm_truth = mdmd.get('llm_theme_llm_truth', '')
    llm_theme = mdmd.get('llm_theme_theme', '')
    
    row = {'input': input, 'input_prompt': input_prompt, 'response': content, 'claim': claim, 'ground': ground, 'warrant': warrant, 
           'llm_theme_human_truth': llm_theme_human_truth, 
           'llm_theme_llm_truth': llm_theme_llm_truth,
           'llm_theme': llm_theme,
           'metadata': md}
    records.append(row)

out_df = pd.DataFrame(records)
save_dir = path.parent
out_df.to_csv(f"{save_dir}/sample_500_meta_result_format_result.csv")

In [2]:
OUTPUT_FILE = r'../results/sample_500_meta_result_format_result_result.jsonl'
path = Path(OUTPUT_FILE)
records = []
with open(path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            print(line)

df = pd.DataFrame(records)

In [9]:
df[2][3]

{'Unnamed: 0': 7,
 'input': 'See how YOU can play a part in the next generation of clean energy and explore a career in nuclear energy.  \n\nLearn more about University Of Michigan’s Nuclear Engineering & Radiation Sciences.',
 'input_prompt': 'Task: Determine whether the claim supports the given theme.\n\nInstructions:\n- Answer "Yes" if the claim supports or promotes the theme.\n- Answer "No" if the claim opposes or argues against the theme.\n- Answer "Not related" if the claim is unrelated to the theme.\n- Base your answer only on the explicit meaning. Do not infer unstated intentions.\n- Output only one of: Yes / No / Not related.\n\nTheme: **"Pro-nuclear advocacy"**\nClaim: [\'You can play a part in the next generation of clean energy\', \'Explore a career in nuclear energy\']\n\nAnswer:\n',
 'response': '{\n    "Claim": [\n        "You can play a part in the next generation of clean energy",\n        "Explore a career in nuclear energy"\n    ],\n    "Ground": [\n        "Not present"\n    ],\n    "Warrant": [\n        "Not present"\n    ]\n}',
 'claim': "['You can play a part in the next generation of clean energy', 'Explore a career in nuclear energy']",
 'ground': "['Not present']",
 'warrant': "['Not present']",
 'llm_theme_human_truth': True,
 'llm_theme_llm_truth': 'Yes',
 'llm_theme': '**"Pro-nuclear advocacy"**',
 'metadata': '{\'id\': 17, \'input\': \'See how YOU can play a part in the next generation of clean energy and explore a career in nuclear energy.  \\n\\nLearn more about University Of Michigan’s Nuclear Engineering & Radiation Sciences.\', \'input_prompt\': \'"""Claim: You can play a part in the next generation of clean energy and explore a career in nuclear energy.\\n\\nGround: Not present\\n\\nWarrant: Not present"""\\n\\n Format the above text in a Python dictionary with values as a list of bullet points.\\n\', \'response\': \'Claim: You can play a part in the next generation of clean energy and explore a career in nuclear energy.\\n\\nGround: Not present\\n\\nWarrant: Not present\', \'metadata\': \'{\\\'ad_archive_id\\\': 1235024824363592, \\\'ad_text\\\': \\\'See how YOU can play a part in the next generation of clean energy and explore a career in nuclear energy.  \\\\n\\\\nLearn more about University Of Michigan’s Nuclear Engineering & Radiation Sciences.\\\', \\\'lda_topic_keywords\\\': \\\'next, share, live, career, whether\\\', \\\'bert_topic_keywords\\\': \\\'nuclear, nuclear energy, nuclear power, career nuclear, career, nuclear industry, reactors, clean reliable, nuclearenergy, nuclear plant\\\', \\\'llm_theme_theme\\\': \\\'**"Pro-nuclear advocacy"**\\\', \\\'llm_theme_summ\\\': \\\'Pro-nuclear advocacy\\\', \\\'lda_keywords_llm_truth\\\': \\\'No\\\', \\\'bert_keywords_llm_truth\\\': \\\'No\\\', \\\'llm_theme_llm_truth\\\': \\\'Yes\\\', \\\'llm_summ_llm_truth\\\': \\\'Yes\\\', \\\'lda_keywords_human_truth\\\': True, \\\'bert_keywords_human_truth\\\': False, \\\'llm_theme_human_truth\\\': True, \\\'llm_summ_human_truth\\\': False, \\\'row\\\': 17, \\\'input_prompt\\\': \\\'"See how YOU can play a part in the next generation of clean energy and explore a career in nuclear energy.  \\\\n\\\\nLearn more about University Of Michigan’s Nuclear Engineering & Radiation Sciences."\\\\n\\\\n Please define above Toulmin components explicitly:\\\\nClaim: disputable position or judgment.\\\\nGround: evidence or reasons explicitly stated.\\\\nWarrant: assumption linking ground to\\\\nclaim.\\\\nInstructions:\\\\n- Components may be absent.\\\\n- Output “Not present” if missing.\\\\n- Do not infer or add unstated informa-\\\\ntion.\\\\n- If text is purely factual or descriptive,\\\\nindicate that no claim is present.\\\'}\', \'row\': 13}',
 'row': 7}

In [34]:
path = Path(r"../important_results/sample_500_meta_gpt_direct_results.csv")
df = pd.read_csv(path)

In [35]:
df.head(10)

,ad_archive_id,ad_text,lda_topic_keywords,bert_topic_keywords,llm_theme_theme,llm_theme_summ,lda_keywords_llm_truth,bert_keywords_llm_truth,llm_theme_llm_truth,llm_summ_llm_truth,lda_keywords_human_truth,bert_keywords_human_truth,llm_theme_human_truth,llm_summ_human_truth,gpt_raw,gpt_toulmin_json,gpt_error
0,718223234007051,🛑🚨🛑🚨Protecting the Endangerment Finding = Prot...,"american, job, economy, america, michigan",NaN,"**""Climate crisis advocacy""**",Clean air advocacy,No,Yes,Yes,Yes,False,False,True,False,"{""claim"":""Protecting the Endangerment Finding ...","{""claim"": ""Protecting the Endangerment Finding...",NaN
1,1228541608145723,Stop Kamala's Radical Plan for America Before ...,"american, job, economy, america, michigan","kamala, kamala harris, harris, fracking, fight...","**""Anti-Harris energy attack""**",Anti-Harris energy attack,Yes,No,Yes,Yes,False,False,True,True,"{""claim"":""Kamala Harris's policies are dangero...","{""claim"": ""Kamala Harris's policies are danger...",NaN
2,1499605261479052,Conduct undergraduate research using next-gen ...,"de, la, el, en, e","ocean, coral, marine, absorbing, currents, mar...","**""Ocean conservation call""**",Ocean conservation call,No,No,No,No,False,False,False,False,"{""claim"":""Not present"",""ground"":""Not present"",...","{""claim"": ""Not present"", ""ground"": ""Not presen...",NaN
3,896143312482283,Governor Whitmer: The people working in the Mi...,"one, people, thing, get, u","michigan, michiganders, dte, whitmer, michigan...","**""Local civic engagement""**",Pro-childcare candidates,No,Yes,Yes,No,True,True,True,True,"{""claim"":""You should vote this Tuesday to keep...","{""claim"": ""You should vote this Tuesday to kee...",NaN
4,1087755083103907,One of the things I love about singing this so...,"one, people, thing, get, u",NaN,"**""Climate crisis advocacy""**",Pro-forest climate action,No,Yes,No,No,False,False,True,True,"{""claim"":""We should find a way to sing through...","{""claim"": ""We should find a way to sing throug...",NaN
5,1053756599549234,Grateful for federal support in North Carolina...,"sustainable, initiative, committed, community,...",NaN,"**""Pro-infrastructure investment""**",Pro-infrastructure investment,No,No,No,No,False,False,True,False,"{""claim"":""Federal support and bipartisan effor...","{""claim"": ""Federal support and bipartisan effo...",NaN
6,586149607698863,Support Sonola Segun’s Recycling Initiative fo...,"sustainable, initiative, committed, community,...","food waste, composting, compost, waste, food s...","**""Pro-recycling advocacy""**",Pro-recycling advocacy,Yes,No,Yes,Yes,False,False,True,False,"{""claim"":""Supporting Sonola Segun’s recycling ...","{""claim"": ""Supporting Sonola Segun’s recycling...",NaN
7,621447447265755,Hoosier communities are benefiting from unleas...,"county, project, revenue, local, commissioner","indiana, hoosier, hoosiers, indiana energy, ho...","**""Pro-infrastructure investment""**",Pro-infrastructure investment,Yes,Yes,Yes,No,False,True,True,True,"{""claim"":""Hoosier communities are benefiting f...","{""claim"": ""Hoosier communities are benefiting ...",NaN
8,360745056975060,Time & time again we see how most of our elect...,"community, hear, training, youth, town",NaN,"**""Public climate input""**",Clean air advocacy,Yes,Yes,Yes,Yes,False,False,True,False,"{""claim"":""We need your help to create the worl...","{""claim"": ""We need your help to create the wor...",NaN
9,2817214565122035,“We’re the third fastest warming city in the n...,"read, good, http, mountain, oregon",NaN,"**""Climate crisis advocacy""**",Pro-infrastructure investment,No,No,No,No,False,False,True,True,"{""claim"":""Not present"",""ground"":""Not present"",...","{""claim"": ""Not present"", ""ground"": ""Not presen...",NaN

In [36]:
gpt_raw = df['gpt_raw']
gpt_toulmin_json = df['gpt_toulmin_json']

In [30]:
len(df)

500

In [10]:
ad_texts = df['ad_text']

In [11]:
ad_texts[0]

'Yesterday we moved on to the dysgenic portion of the program with Donald Trump and Robert F. Kennedy Jr.’s press conference on autism where the MAGA/MAHA nexus made it clear that they view autistic people as mistakes; unfortunate victims of weak mothers who must be “cured.”'

In [38]:
print(gpt_raw[10])

{"claim":"A strong majority of Alaskans support using state and federal dollars to develop affordable, local energy.","ground":"Not present","warrant":"Not present"}

In [19]:
print(gpt_toulmin_json[20])

nan

In [39]:
path = Path(r"../important_results/sample_500_meta_gpt_results.csv")
df = pd.read_csv(path)

In [40]:
df.head(10)

,ad_archive_id,ad_text,lda_topic_keywords,bert_topic_keywords,llm_theme_theme,llm_theme_summ,lda_keywords_llm_truth,bert_keywords_llm_truth,llm_theme_llm_truth,llm_summ_llm_truth,lda_keywords_human_truth,bert_keywords_human_truth,llm_theme_human_truth,llm_summ_human_truth,gpt_raw,gpt_toulmin_json,gpt_error
0,718223234007051,🛑🚨🛑🚨Protecting the Endangerment Finding = Prot...,"american, job, economy, america, michigan",NaN,"**""Climate crisis advocacy""**",Clean air advocacy,No,Yes,Yes,Yes,False,False,True,False,"{""claim"":""Protecting the Endangerment Finding ...","{""claim"": ""Protecting the Endangerment Finding...",NaN
1,1228541608145723,Stop Kamala's Radical Plan for America Before ...,"american, job, economy, america, michigan","kamala, kamala harris, harris, fracking, fight...","**""Anti-Harris energy attack""**",Anti-Harris energy attack,Yes,No,Yes,Yes,False,False,True,True,"{""claim"":""Kamala Harris's policies are dangero...","{""claim"": ""Kamala Harris's policies are danger...",NaN
2,1499605261479052,Conduct undergraduate research using next-gen ...,"de, la, el, en, e","ocean, coral, marine, absorbing, currents, mar...","**""Ocean conservation call""**",Ocean conservation call,No,No,No,No,False,False,False,False,"{""claim"":""Not present"",""ground"":""Not present"",...","{""claim"": ""Not present"", ""ground"": ""Not presen...",NaN
3,896143312482283,Governor Whitmer: The people working in the Mi...,"one, people, thing, get, u","michigan, michiganders, dte, whitmer, michigan...","**""Local civic engagement""**",Pro-childcare candidates,No,Yes,Yes,No,True,True,True,True,"{""claim"":""You should vote this Tuesday to keep...","{""claim"": ""You should vote this Tuesday to kee...",NaN
4,1087755083103907,One of the things I love about singing this so...,"one, people, thing, get, u",NaN,"**""Climate crisis advocacy""**",Pro-forest climate action,No,Yes,No,No,False,False,True,True,"{""claim"":""We should find ways to sing through ...","{""claim"": ""We should find ways to sing through...",NaN
5,1053756599549234,Grateful for federal support in North Carolina...,"sustainable, initiative, committed, community,...",NaN,"**""Pro-infrastructure investment""**",Pro-infrastructure investment,No,No,No,No,False,False,True,False,"{""claim"":""Federal support and bipartisan effor...","{""claim"": ""Federal support and bipartisan effo...",NaN
6,586149607698863,Support Sonola Segun’s Recycling Initiative fo...,"sustainable, initiative, committed, community,...","food waste, composting, compost, waste, food s...","**""Pro-recycling advocacy""**",Pro-recycling advocacy,Yes,No,Yes,Yes,False,False,True,False,"{""claim"":""You should support Sonola Segun’s Re...","{""claim"": ""You should support Sonola Segun’s R...",NaN
7,621447447265755,Hoosier communities are benefiting from unleas...,"county, project, revenue, local, commissioner","indiana, hoosier, hoosiers, indiana energy, ho...","**""Pro-infrastructure investment""**",Pro-infrastructure investment,Yes,Yes,Yes,No,False,True,True,True,"{""claim"":""Hoosier communities are benefiting f...","{""claim"": ""Hoosier communities are benefiting ...",NaN
8,360745056975060,Time & time again we see how most of our elect...,"community, hear, training, youth, town",NaN,"**""Public climate input""**",Clean air advocacy,Yes,Yes,Yes,Yes,False,False,True,False,"{""claim"":""We need your help to create the worl...","{""claim"": ""We need your help to create the wor...",NaN
9,2817214565122035,“We’re the third fastest warming city in the n...,"read, good, http, mountain, oregon",NaN,"**""Climate crisis advocacy""**",Pro-infrastructure investment,No,No,No,No,False,False,True,True,"{""claim"":""Not present"",""ground"":""“We’re the th...","{""claim"": ""Not present"", ""ground"": ""“We’re the...",NaN

In [10]:
800*5000

4000000

In [3]:
from openai import AsyncOpenAI
client = AsyncOpenAI(api_key="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")

In [4]:
resp = await client.responses.create(
        model="gpt-5-mini",
        input=[
            {"role": "system", "content": "Hello?"},
            {"role": "user", "content": "what is your name?"},
        ],
        max_output_tokens=256,
    )

In [12]:
SYSTEM_PROMPT = """You are an information extraction system for Toulmin argument components.

Definitions:
- Claim: a disputable position, judgment, or persuasive statement.
- Ground: evidence or factual support explicitly stated in the text.
- Warrant: a reasoning statement that explicitly explains why the ground supports the claim.

Important rules (read carefully):
- Extract ONLY what is explicitly stated.
- Do NOT infer, assume, or add common-sense reasoning.
- If a component is not explicitly written in the text, output "Not present".
- Warrants are RARE. Most texts do NOT contain an explicit warrant.
- Do NOT create a warrant unless the reasoning is clearly and explicitly stated.
- If the text is purely factual, descriptive, or promotional without a disputable position, the claim is "Not present".
- Return STRICT JSON only:
{"claim": "...", "ground": "...", "warrant": "..."}"""

FEWSHOT_BLOCK = """
Example 1
Text:
Upgrade your Teaching Toolbox! Uncover free interactive tools with standout resources for teaching fiscal policy. Transform your lessons into engaging, unforgettable experiences.

Output:
{"claim":"Free interactive tools can transform fiscal policy lessons into engaging and effective learning experiences.","ground":"Not present","warrant":"Not present"}

Example 2
Text:
Accelerating the future of energy, together

Output:
{"claim":"Not present","ground":"Not present","warrant":"Not present"}

Example 3
Text:
Our spray foam insulation helps reduce energy waste and supports a more sustainable future.

Output:
{"claim":"Using this insulation supports a more sustainable future.","ground":"Our spray foam insulation helps reduce energy waste.","warrant":"Not present"}

Example 4 (explicit warrant case)
Text:
Our insulation reduces energy waste. Because reducing energy waste lowers carbon emissions, it helps protect the environment.

Output:
{"claim":"Using this insulation helps protect the environment.","ground":"Our insulation reduces energy waste.","warrant":"Reducing energy waste lowers carbon emissions."}
""".strip()

In [13]:
def build_user_prompt(ad_text: str) -> str:
    return f"""{FEWSHOT_BLOCK}

Now analyze the following text.

Text:
{ad_text}

Output:
""".strip()

In [19]:
model = "gpt-4.1"
ad_text = r"Yesterday we moved on to the dysgenic portion of the program with Donald Trump and Robert F. Kennedy Jr.’s press conference on autism where the MAGA/MAHA nexus made it clear that they view autistic people as mistakes; unfortunate victims of weak mothers who must be “cured.”"
resp = await client.responses.create(
        model=model,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_user_prompt(ad_text)},
        ],
        max_output_tokens=512,
    )

In [21]:
print(resp.output_text)

{"claim":"The MAGA/MAHA nexus made it clear that they view autistic people as mistakes; unfortunate victims of weak mothers who must be 'cured.'","ground":"Yesterday we moved on to the dysgenic portion of the program with Donald Trump and Robert F. Kennedy Jr.’s press conference on autism.","warrant":"Not present"}

In [27]:
3000 * 800

2400000